const std = @import("std");
const testing = std.testing;

/// [u8] gives us 8-bits of storage to save indexes. Meaning we can essentially store `2^(8-1) = 0-255` indexes.
///
/// Total of 256 element indexes, which is more than enough for our use case to store indexes of elements from an Array
/// as value reference in our map.
///
/// Keys are of type `[]const u8`.
const IndexMap = std.StaticStringMap(u8);

pub fn HashBackedArray(comptime V: type) type {
    return struct {
        const Self = @This();

        _array: []const V,
        _index_map: IndexMap,
        len: usize,

        pub const KV = struct { []const u8, V };

        pub fn initComptime(comptime Arr: []const V, comptime key: fn (e: V) []const u8) Self {
            const kvs = comptime blk: {
                var arr: [Arr.len]KV = undefined;

                for (Arr, 0..) |a, i| {
                    arr[i] = .{ key(a), i };
                }

                break :blk arr[0..];
            };

            return .{
                ._array = Arr,
                ._index_map = IndexMap.initComptime(kvs),
                .len = Arr.len,
            };
        }

        pub fn has(self: *Self, key: []const u8) bool {
            return self._index_map.has(key);
        }

        pub fn values(self: *Self) []const V {
            return self._array;
        }

        pub fn keys(self: *Self) []const []const u8 {
            return self._index_map.keys();
        }

        pub fn get(self: *Self, key: []const u8) ?V {
            const item_idx = self._index_map.get(key) orelse
                return null;

            return self._array[item_idx];
        }

        pub fn indexOf(self: *Self, key: []const u8) ?u8 {
            return self._index_map.get(key);
        }
    };
}

fn genKey(num: usize) []const u8 {
    return std.fmt.comptimePrint("{d}", .{num});
}

test "Initializes" {
    const arr: []const usize = &.{ 1, 5, 6, 7, 2, 4, 9, 8 };

    var hba = HashBackedArray(usize).initComptime(arr, genKey);

    try testing.expectEqual(arr.len, hba.len);
    try testing.expectEqual(arr.len, hba.keys().len);
    try testing.expectEqual(arr.len, hba.values().len);
}

test "has() works correctly" {
    const arr: []const usize = &.{ 1, 5, 6, 7, 2, 4, 9, 8 };

    var hba = HashBackedArray(usize).initComptime(arr, genKey);

    try testing.expect(hba.has("1"));
    try testing.expect(hba.has("5"));
    try testing.expect(hba.has("6"));
    try testing.expect(hba.has("7"));
    try testing.expect(hba.has("2"));
    try testing.expect(hba.has("4"));
    try testing.expect(hba.has("9"));
    try testing.expect(hba.has("8"));

    try testing.expectEqual(false, hba.has("10"));
    try testing.expectEqual(false, hba.has("0"));
    try testing.expectEqual(false, hba.has("3"));
}

test "values() returns an array of elements" {
    const arr: []const usize = &.{ 1, 5, 6, 7, 2, 4, 9, 8 };

    var hba = HashBackedArray(usize).initComptime(arr, genKey);

    try testing.expectEqualSlices(usize, arr, hba.values());
}

test "keys() returns an array of keys generated by lambda on comptime" {
    const arr: []const usize = &.{ 1, 5, 6, 7, 2, 4, 9, 8 };
    const key_arr: []const []const u8 = &.{ "1", "5", "6", "7", "2", "4", "9", "8" };

    var hba = HashBackedArray(usize).initComptime(arr, genKey);

    try testing.expectEqualSlices(usize, arr, hba.values());
    try testing.expectEqualSlices([]const u8, key_arr, hba.keys());
}

test "get() works correctly" {
    const arr: []const usize = &.{ 1, 5, 6, 7, 2, 4, 9, 8 };

    var hba = HashBackedArray(usize).initComptime(arr, genKey);

    try testing.expectEqual(2, hba.get("2"));
    try testing.expectEqual(null, hba.get("3"));
    try testing.expectEqual(null, hba.get("-3"));
}

test "indexOf() returns the index of element in the array" {
    const arr: []const usize = &.{ 1, 5, 6, 7, 2, 4, 9, 8 };

    var hba = HashBackedArray(usize).initComptime(arr, genKey);

    try testing.expectEqual(0, hba.indexOf("1"));
    try testing.expectEqual(4, hba.indexOf("2"));
    try testing.expectEqual(7, hba.indexOf("8"));

    try testing.expectEqual(null, hba.indexOf("10"));
    try testing.expectEqual(null, hba.indexOf("3"));
}
